# site properties and page defaults
title: Depledge Lab
subtitle: Institute of Virology, Hannover Medical School
description: DepledgeLab focuses on understanding how human herpesviruses persist following infection and how this is influenced by different aspects of RNA biology. Here, exciting web-lab, high performance computing bioinformatics and supportive colleagues meet to create new research.
header: images/background_dna.png
footer: images/background_dna.png
proofer: false

# site social media and other links
links:
  email: depledge.daniel@mh-hannover.de
  github: DepledgeLab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
